/* =========================================================
   NutriQuest — glosario_embedded.js
   Embeds data/glosario.json into JS to avoid any fetch during startup.
   This makes the first load instant (no network required).
   ========================================================= */

window.GLOSARIO_TERMS = [
  {"id":1,"mundo":1,"nivel":1,"termino":"ADITIVO ALIMENTARIO","definicion":"Sustancia añadida a los alimentos en pequeñas cantidades para mejorar su conservación, valor nutritivo, características organolépticas o desempeño productivo del animal.","importancia":"Permite mejorar la eficiencia alimenticia, mantener la calidad del alimento y optimizar la salud y producción animal.","icono":"➕"},
  {"id":2,"mundo":1,"nivel":2,"termino":"ALIMENTACIÓN","definicion":"Proceso mediante el cual los animales consumen, seleccionan y utilizan alimentos para obtener energía y nutrientes necesarios para vivir y producir.","importancia":"Una alimentación adecuada permite mantener la salud, crecimiento, reproducción y productividad del animal.","icono":"🍽️"},
  {"id":3,"mundo":1,"nivel":3,"termino":"ALIMENTO","definicion":"Producto de origen vegetal, animal o mineral que contiene nutrientes aprovechables por el organismo animal.","importancia":"Es la fuente de nutrientes necesarios para cubrir las funciones metabólicas y productivas del animal.","icono":"🥣"},
  {"id":4,"mundo":1,"nivel":4,"termino":"ANÁLISIS GARANTIZADO","definicion":"Declaración del contenido mínimo o máximo de nutrientes presentes en un alimento balanceado, como proteína, grasa, fibra, humedad y minerales.","importancia":"Permite conocer la composición del alimento y evaluar si cumple con los requerimientos nutricionales del animal.","icono":"📋"},
  {"id":5,"mundo":1,"nivel":5,"termino":"CALORÍA","definicion":"Unidad de medida utilizada para expresar la cantidad de energía que aporta un alimento.","importancia":"Permite determinar la energía disponible para mantenimiento, crecimiento, reproducción y producción.","icono":"🔥"},
  {"id":6,"mundo":2,"nivel":1,"termino":"CONDICIÓN CORPORAL","definicion":"Método de evaluación visual y palpatoria que estima las reservas corporales de grasa y músculo del animal.","importancia":"Ayuda a valorar el estado nutricional y ajustar la alimentación según las necesidades del animal.","icono":"📏"},
  {"id":7,"mundo":2,"nivel":2,"termino":"CONSUMO VOLUNTARIO","definicion":"Cantidad de alimento que un animal consume espontáneamente cuando tiene acceso libre al mismo.","importancia":"Determina la cantidad real de nutrientes ingeridos y afecta directamente la producción animal.","icono":"🧑‍🌾"},
  {"id":8,"mundo":2,"nivel":3,"termino":"CORRECTORES NUTRICIONALES","definicion":"Productos formulados para corregir deficiencias específicas de nutrientes en una dieta.","importancia":"Permiten equilibrar la alimentación y evitar problemas derivados de carencias nutricionales.","icono":"🛠️"},
  {"id":9,"mundo":2,"nivel":4,"termino":"DENSIDAD ENERGÉTICA","definicion":"Cantidad de energía disponible contenida en una unidad de alimento, generalmente expresada por kilogramo de materia seca.","importancia":"Determina la capacidad del alimento para cubrir las demandas energéticas del animal.","icono":"⚡"},
  {"id":10,"mundo":2,"nivel":5,"termino":"DIETA","definicion":"Conjunto de alimentos y nutrientes consumidos por un animal durante un periodo determinado.","importancia":"Una dieta equilibrada garantiza el aporte adecuado de nutrientes para mantener la salud y productividad.","icono":"📚"},
  {"id":11,"mundo":3,"nivel":1,"termino":"DIGESTIBLE","definicion":"Fracción del alimento que puede ser degradada y absorbida por el sistema digestivo del animal.","importancia":"Indica la cantidad de nutrientes que realmente pueden ser utilizados por el organismo.","icono":"🔎"},
  {"id":12,"mundo":3,"nivel":2,"termino":"DIGESTIBILIDAD","definicion":"Porcentaje del alimento ingerido que es aprovechado por el animal después del proceso digestivo.","importancia":"Permite evaluar la calidad nutricional de los alimentos y su aprovechamiento.","icono":"%"},
  {"id":13,"mundo":3,"nivel":3,"termino":"ENZIMAS","definicion":"Proteínas que aceleran procesos digestivos y metabólicos mediante la degradación de nutrientes.","importancia":"Mejoran la utilización de los alimentos, favorecen la digestión y pueden aumentar la eficiencia productiva.","icono":"🧬"},
  {"id":14,"mundo":3,"nivel":4,"termino":"ESPECTROSCOPIA DE REFLECTANCIA EN EL INFRARROJO CERCANO (NIRS)","definicion":"Método analítico que utiliza luz infrarroja para determinar la composición nutricional de los alimentos.","importancia":"Permite analizar rápidamente nutrientes como proteína, fibra y humedad sin destruir la muestra.","icono":"📡"},
  {"id":15,"mundo":3,"nivel":5,"termino":"EXTRUSIÓN","definicion":"Proceso industrial donde el alimento es sometido a presión, temperatura y humedad para modificar sus características físicas y nutricionales.","importancia":"Mejora la digestibilidad, estabilidad y aprovechamiento de ciertos alimentos.","icono":"🏭"},
  {"id":16,"mundo":4,"nivel":1,"termino":"FACTORES ANTINUTRICIONALES (FAN)","definicion":"Compuestos presentes en algunos alimentos que reducen la digestión, absorción o utilización de nutrientes.","importancia":"Pueden disminuir el rendimiento productivo y causar efectos negativos en la salud animal.","icono":"⛔"},
  {"id":17,"mundo":4,"nivel":2,"termino":"FORRAJE","definicion":"Material vegetal compuesto por pastos, hojas, tallos y leguminosas utilizado como alimento principal de animales herbívoros, especialmente rumiantes.","importancia":"Es la principal fuente de fibra necesaria para mantener una fermentación ruminal adecuada y una buena salud digestiva.","icono":"🌾"},
  {"id":18,"mundo":4,"nivel":3,"termino":"INGREDIENTE","definicion":"Cada uno de los componentes utilizados para formular un alimento o dieta animal.","importancia":"Determina la calidad nutricional, disponibilidad y costo del alimento.","icono":"🧩"},
  {"id":19,"mundo":4,"nivel":4,"termino":"JOULE","definicion":"Unidad internacional utilizada para medir energía, incluyendo la energía contenida en los alimentos.","importancia":"Permite expresar y comparar el aporte energético de diferentes alimentos.","icono":"⚙️"},
  {"id":20,"mundo":4,"nivel":5,"termino":"MATERIA PRIMA","definicion":"Producto básico de origen vegetal, animal o mineral utilizado para elaborar alimentos balanceados.","importancia":"Su calidad influye directamente en el valor nutritivo del alimento final.","icono":"🌱"},
  {"id":21,"mundo":5,"nivel":1,"termino":"MATERIA SECA","definicion":"Fracción del alimento que queda después de eliminar el agua y contiene los nutrientes reales del alimento.","importancia":"Permite comparar correctamente el valor nutritivo de diferentes alimentos.","icono":"💧"},
  {"id":22,"mundo":5,"nivel":2,"termino":"NÚCLEO","definicion":"Mezcla concentrada de vitaminas, minerales, aminoácidos y otros nutrientes utilizada para complementar alimentos balanceados.","importancia":"Ayuda a formular dietas completas y equilibradas.","icono":"🧠"},
  {"id":23,"mundo":5,"nivel":3,"termino":"NUTRACÉUTICO","definicion":"Producto derivado de alimentos que proporciona beneficios adicionales para la salud más allá de la nutrición básica.","importancia":"Puede mejorar funciones fisiológicas y prevenir alteraciones metabólicas.","icono":"🩺"},
  {"id":24,"mundo":5,"nivel":4,"termino":"NUTRICIÓN","definicion":"Ciencia que estudia los nutrientes, su metabolismo y la relación entre alimentación y salud animal.","importancia":"Permite formular dietas adecuadas para mantener salud y producción.","icono":"📖"},
  {"id":25,"mundo":5,"nivel":5,"termino":"NUTRIGENÓMICA","definicion":"Disciplina que estudia cómo los nutrientes afectan la expresión de los genes del animal.","importancia":"Permite desarrollar estrategias nutricionales más precisas según las características del animal.","icono":"🧬"},
  {"id":26,"mundo":6,"nivel":1,"termino":"NUTRIENTES","definicion":"Componentes químicos de los alimentos necesarios para funciones como crecimiento, mantenimiento y reproducción.","importancia":"Son indispensables para el metabolismo y funcionamiento normal del organismo.","icono":"🧪"},
  {"id":27,"mundo":6,"nivel":2,"termino":"NUTRIENTE ESENCIAL","definicion":"Nutriente que el organismo no puede producir en cantidades suficientes y debe obtener mediante la dieta.","importancia":"Su ausencia puede provocar deficiencias y problemas productivos.","icono":"⭐"},
  {"id":28,"mundo":6,"nivel":3,"termino":"NUTRIENTE NO ESENCIAL","definicion":"Nutriente que el organismo puede sintetizar a partir de otros compuestos.","importancia":"Aunque no sea necesario consumirlo directamente, participa en procesos metabólicos importantes.","icono":"🔄"},
  {"id":29,"mundo":6,"nivel":4,"termino":"PALATABILIDAD","definicion":"Grado de aceptación y gusto que tiene un alimento para un animal.","importancia":"Influye en el consumo voluntario y aprovechamiento de la dieta.","icono":"😋"},
  {"id":30,"mundo":6,"nivel":5,"termino":"PELETIZADO","definicion":"Proceso donde el alimento es compactado en pequeñas partículas cilíndricas llamadas pellets.","importancia":"Reduce desperdicios, mejora manejo y puede aumentar la eficiencia alimenticia.","icono":"📦"},
  {"id":31,"mundo":7,"nivel":1,"termino":"PESO METABÓLICO","definicion":"Peso corporal elevado a la potencia 0.75 utilizado para estimar necesidades energéticas del animal.","importancia":"Permite calcular requerimientos nutricionales comparables entre animales de diferentes tamaños.","icono":"⚖️"},
  {"id":32,"mundo":7,"nivel":2,"termino":"PESO VIVO","definicion":"Peso total del animal antes del sacrificio o evaluación productiva.","importancia":"Se utiliza para calcular dosis, requerimientos nutricionales y evaluar crecimiento.","icono":"🧍"},
  {"id":33,"mundo":7,"nivel":3,"termino":"PIENSO (ALIMENTO BALANCEADO)","definicion":"Alimento elaborado que contiene una combinación equilibrada de nutrientes para cubrir las necesidades del animal.","importancia":"Permite obtener mejores resultados productivos mediante una nutrición controlada.","icono":"⚖️"},
  {"id":34,"mundo":7,"nivel":4,"termino":"POSTBIÓTICO","definicion":"Compuestos producidos por microorganismos beneficiosos durante su crecimiento o fermentación.","importancia":"Pueden favorecer la salud intestinal y mejorar la respuesta inmunitaria.","icono":"🧫"},
  {"id":35,"mundo":7,"nivel":5,"termino":"PREBIÓTICO","definicion":"Sustancia no digerible que estimula el crecimiento de microorganismos beneficiosos del intestino.","importancia":"Ayuda a mantener una microbiota intestinal saludable.","icono":"🧩"},
  {"id":36,"mundo":8,"nivel":1,"termino":"PREINICIADOR","definicion":"Alimento especializado suministrado en etapas tempranas de vida para estimular el desarrollo digestivo.","importancia":"Favorece la adaptación del sistema digestivo y mejora el crecimiento inicial.","icono":"🍼"},
  {"id":37,"mundo":8,"nivel":2,"termino":"PREMEZCLA","definicion":"Mezcla concentrada de vitaminas, minerales y aditivos incorporada a alimentos balanceados.","importancia":"Garantiza cantidades adecuadas de micronutrientes en la dieta.","icono":"📦"},
  {"id":38,"mundo":8,"nivel":3,"termino":"PROBIÓTICO","definicion":"Microorganismos vivos que aportan beneficios al animal cuando se administran en cantidades adecuadas.","importancia":"Favorecen el equilibrio de la microbiota intestinal y la salud digestiva.","icono":"🦠"},
  {"id":39,"mundo":8,"nivel":4,"termino":"PROMOTORES DE CRECIMIENTO","definicion":"Sustancias utilizadas para mejorar la ganancia de peso, eficiencia alimenticia o producción animal.","importancia":"Permiten aumentar la productividad mediante un mejor aprovechamiento de nutrientes.","icono":"🚀"},
  {"id":40,"mundo":8,"nivel":5,"termino":"RACIÓN","definicion":"Cantidad total de alimento suministrada a un animal durante 24 horas.","importancia":"Permite cubrir exactamente los requerimientos nutricionales diarios.","icono":"🥣"},
  {"id":41,"mundo":9,"nivel":1,"termino":"REQUERIMIENTO NUTRICIONAL","definicion":"Cantidad de nutrientes necesarios para mantener funciones fisiológicas y alcanzar un nivel productivo determinado.","importancia":"Sirve como base para formular dietas adecuadas.","icono":"📊"},
  {"id":42,"mundo":9,"nivel":2,"termino":"SIMBIÓTICO","definicion":"Combinación de probióticos y prebióticos que trabajan conjuntamente para mejorar la salud intestinal.","importancia":"Favorece una microbiota equilibrada y mejora el aprovechamiento nutricional.","icono":"🔗"},
  {"id":43,"mundo":9,"nivel":3,"termino":"SUPLEMENTO NUTRICIONAL","definicion":"Producto añadido a la dieta para aportar nutrientes que pueden estar deficientes.","importancia":"Ayuda a corregir deficiencias y mejorar desempeño productivo.","icono":"➕"},
  {"id":44,"mundo":9,"nivel":4,"termino":"UNIDAD FORRAJERA CARNE (UFC) Y UNIDAD FORRAJERA LECHE (UFL)","definicion":"Sistemas de valoración energética utilizados para estimar el aporte de energía de los alimentos en producción de carne y leche.","importancia":"Permiten formular dietas según las necesidades energéticas de animales productores.","icono":"⚡"},
  {"id":45,"mundo":9,"nivel":5,"termino":"VALOR NUTRITIVO","definicion":"Conjunto de características que determinan la calidad de un alimento, incluyendo nutrientes, digestibilidad y energía disponible.","importancia":"Permite seleccionar alimentos adecuados para cubrir las necesidades del animal.","icono":"📘"}
];

window.GLOSARIO_SIG = (function(){
  const terms = window.GLOSARIO_TERMS || [];
  const count = terms.length;
  const ids = terms.slice(0, 60).map(t => t.id).join(',');
  return count + '|' + ids;
})();

